# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caozuoxitong.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 348)
        MainWindow.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(81,187,98);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        # 标题
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(200, 40, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title.setFont(font)
        self.title.setObjectName("title")


        #显示框
        self.file_dir_show = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.file_dir_show.setGeometry(QtCore.QRect(210, 170, 361, 41))
        self.file_dir_show.setObjectName("file_dir_show")
        self.file_dir_show.setPlainText("system_src")


        #选择文件
        self.xuanze_file_dir = QtWidgets.QPushButton(self.centralwidget)
        self.xuanze_file_dir.setGeometry(QtCore.QRect(30, 170, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xuanze_file_dir.setFont(font)
        self.xuanze_file_dir.setObjectName("xuanze_file_dir")

        #批量重命名
        self.rename = QtWidgets.QPushButton(self.centralwidget)
        self.rename.setGeometry(QtCore.QRect(30, 270, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rename.setFont(font)
        self.rename.setObjectName("rename")


        #
        self.txt_to_excel = QtWidgets.QPushButton(self.centralwidget)
        self.txt_to_excel.setGeometry(QtCore.QRect(210, 270, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_to_excel.setFont(font)
        self.txt_to_excel.setObjectName("txt_to_excel")


        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "操作系统基线整理工具_By_Garck"))
        self.xuanze_file_dir.setText(_translate("MainWindow", "选择文件夹"))
        self.rename.setText(_translate("MainWindow", "批量重命名"))
        self.txt_to_excel.setText(_translate("MainWindow", "TXT转Excel"))
        self.title.setText(_translate("MainWindow", "操作系统基线整理"))
